services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    env_file:
      - .dev.env
    container_name: web_comment
    restart: always
    command: [ "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4" ]


  postgres:
    image: postgres:15-alpine
    env_file:
      - .dev.env
    container_name: postgres_comment
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "pgdata_comment:/var/lib/postgresql/data"

  redis:
    image: redis:7-alpine
    container_name: redis_comment
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "redis_comment:/data"

volumes:
  pgdata_comment:
  redis_comment: