[project]
name = "commentnest"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.5",
    "fastapi[all]>=0.117.1",
    "pydantic-settings>=2.10.1",
    "sqlalchemy>=2.0.43",
]
